{
 "title": "mongodb_sharding_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(mongodb_dbstats_dataSize,database)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(mongodb_collstats_storageStats_count,collection)"
    }
   },
   {
    "name": "TestName",
    "query": {
     "query": "label_values(mongo_test_duration_seconds,test_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health & Capacity (KPIs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Connections (mongos)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{alias=\"mongos-router\", cluster=\"mongo-cluster\", instance=\"mongo-exporter:9216\", job=\"mongodb\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Data Size (Cluster Wide)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_dataSize{database=\"$database\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Document Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mongodb_collstats_storageStats_count{collection=\"$collection\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sharding & Balancing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_dbstats_raw_shard1ReplSet_shard1_27017_dataSize{database=\"$database\"}",
       "legendFormat": "Shard 1"
      },
      {
       "expr": "mongodb_dbstats_raw_shard2ReplSet_shard2_27017_dataSize{database=\"$database\"}",
       "legendFormat": "Shard 2"
      },
      {
       "expr": "mongodb_dbstats_raw_shard3ReplSet_shard3_27017_dataSize{database=\"$database\"}",
       "legendFormat": "Shard 3"
      }
     ]
    },
    {
     "title": "Chunk Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_mongos_sharding_shard_chunks_total",
       "legendFormat": "{{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage & Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Breakdown (Data vs. Index)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(mongodb_dbstats_dataSize{database=~\"$database\"})",
       "legendFormat": "Data Size"
      },
      {
       "expr": "sum(mongodb_dbstats_indexSize{database=~\"$database\"})",
       "legendFormat": "Index Size"
      },
      {
       "expr": "sum(mongodb_dbstats_dataSize{database=~\"$database\"}) + sum(mongodb_dbstats_indexSize{database=~\"$database\"}) ",
       "legendFormat": "total size"
      }
     ]
    },
    {
     "title": "Average Document Size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(mongodb_collstats_storageStats_avgObjSize{collection=~\"$collection\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance & Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Throughput (Ops/Sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\"}[1m]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\"}[1m]))",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\"}[1m]))",
       "legendFormat": "Commands"
      }
     ]
    },
    {
     "title": "Average Operation Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_latency{collection=~\"$collection\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\"}[1m]))",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_latency{collection=~\"$collection\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\"}[1m]))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_latency{collection=~\"$collection\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\"}[1m]))",
       "legendFormat": "Command Latency"
      }
     ]
    },
    {
     "title": "Cluster Throughput (Ops/Sec) [shard 1]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m]))",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m]))",
       "legendFormat": "Commands"
      }
     ]
    },
    {
     "title": "Cluster Throughput (Ops/Sec) [shard 2]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m]))",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m]))",
       "legendFormat": "Commands"
      }
     ]
    },
    {
     "title": "Cluster Throughput (Ops/Sec) [shard 3]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m]))",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m]))",
       "legendFormat": "Commands"
      }
     ]
    },
    {
     "title": "Average Operation Latency [Shard 1]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_latency{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m]))",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_latency{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m]))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_latency{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\", shard=\"shard1ReplSet\"}[1m]))",
       "legendFormat": "Command Latency"
      }
     ]
    },
    {
     "title": "Average Operation Latency [Shard 2]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_latency{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m]))",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_latency{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m]))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_latency{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\", shard=\"shard2ReplSet\"}[1m]))",
       "legendFormat": "Command Latency"
      }
     ]
    },
    {
     "title": "Average Operation Latency [Shard 3]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_reads_latency{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_reads_ops{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m]))",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_writes_latency{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_writes_ops{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m]))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "sum(rate(mongodb_collstats_latencyStats_commands_latency{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m])) / sum(rate(mongodb_collstats_latencyStats_commands_ops{collection=~\"$collection\", shard=\"shard3ReplSet\"}[1m]))",
       "legendFormat": "Command Latency"
      }
     ]
    }
   ]
  },
  { "title": "Synthetic Test Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Test Duration (Latency)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_test_duration_seconds{test_name=\"$TestName\"}",
     "legendFormat": "{{test_type}}"
    }
   ]
  },
  {
   "title": "Index Efficiency (Scanned vs Returned)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_test_docs_examined{test_name=\"$TestName\"}",
     "legendFormat": "Examined"
    },
    {
     "expr": "mongo_test_docs_returned{test_name=\"$TestName\"}",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Winning Plan (Index vs. CollScan)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_test_winning_plan{test_name=~\"$TestName\"}",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Documents Modified",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mongo_test_docs_modified{test_name=\"$TestName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mongo_test_errors_total{test_name=~\"$TestName\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topology Target (Scatter vs. Sharded)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_test_shards_hit{test_name=~\"$TestName\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}